### ISSUE TITLE
Не работает поиск по url, описанным в pages.xml после url с вызовами LinkUtility 

### ISSUE THREAD

**Issue by antyblin** [hrefr/eazestorm#4]
Файлы находятся только для / и nwst.ru/. 
Для всех остальных url в любом варианте (путь без домена, путь с доменом, eaze uri) совпадений нет.
site name в [pages.xml](https://dl.dropboxusercontent.com/u/931412/pages.xml) указан и совпадает с site name из [sites.xml](https://dl.dropboxusercontent.com/u/931412/sites.xml).

Проверял на PhpStorm 8.0.3 и EAP PS-141.176, eazestorm v2.2.1

**Comment by hrefr** [comment]
Привет.
Проверяла различные варианты урлов из представленного pages.xml, например:
/foto/search/
nwst.ru/foto/search/
http://nwst/foto/search/
/sitemap.xml
nwst.ru/sitemap.xml
http://nwst/sitemap.xml
controls://cart/
и т.д. (имя домена не играет значения в силу старого бага)
Все варианты работают, кроме урлов типа "/{LinkUtility::GetNewsBaseUrl()}/"
Список файлов показывается только для существующих экшенов (с существующими путями) и существующих шаблонов.

Чтобы понять, в чем проблема, мне понадобится для тестирования полностью весь твой проект (как минимум содержимое папок web/etc/, web/lib/, web/lib.eaze/), а также некоторый список конкретных неработающих url.

**Comment by antyblin** [comment]
Теперь у меня при поиске вообще эксепшн валится:
`Argument for @NotNull parameter 'file' of com/intellij/psi/impl/PsiManagerImpl.findFile must not be null`

**Comment by hrefr** [comment]
Иксепшн возникает из-за отсутсвия файла sites.xml в папке web/etc/conf/
Исправлено в версии 2.2.2. Теперь вместо иксепшена будет выводится соответствующее сообщение в EventLog с предупреждением об отсутствии файла.
После обновления и исправления ошибки наличия файла прошу проверить изначальную проблему.

**Comment by antyblin** [comment]
Нашёл причину: в поиске участвуют только урлы, указанные до урлов типа /{LinkUtility::GetNewsBaseUrl()}.
Например, если разместить блок `page uri="/sitemap.xml"` сразу после `page uri="/"`, то всё успешно находится.

По поводу /{LinkUtility::GetNewsBaseUrl()} есть идея, как исправить. Сюда писать или новый ишью заводить?

**Comment by hrefr** [comment]
Давай сюда уже, там посмотрим, стоит ли выделять в отдельный ишью. Если что, можно будет уточнить заголовок.

**Comment by antyblin** [comment]
Можем сначала искать по файлу cache/pages_*.xml (там в page uri находятся уже результаты вызовов методов вроде LinkUtility::GetNewsBaseUrl()), а при его отсутствии — по web/pages.xml.

**Comment by hrefr** [comment]
Я тут вижу, на самом деле, 2 задачи:
1. Баг поиска uri, если он объявлен после uri вида  `/{LinkUtility::GetNewsBaseUrl()}`. Причину я уже выяснила, она довольно банальна - необработанная ошибка компиляции регулярного выражения. 
Предложенный тобой метод лишь частично решит задачу, поскольку наличие файла (или файлов?) `cache/pages_*.xml` не гарантировано. Ну и баг надо исправлять.
Я уточню заголовок текущей ишью.
2. Предложенный тобой вариант, на самом деле, порождает возможность введения новой фичи - поиск по скомпилированным урлам LinkUtility. 
Если интересует введение этой фичи, можно завести отдельную ишью и описать там подробности (в частности, описание имен и содержимого файлов `cache/pages_*.xml`)

**Comment by antyblin** [comment]
Изначально я как раз про эту фичу и хотел написать, пока не натолкнулся на баг.
