### ISSUE TITLE
Добавить поддержку поиска по динамическим page uri вида /{LinkUtility::GetNewsBaseUrl()}

### ISSUE THREAD

**Issue by antyblin** [hrefr/eazestorm#5]
Единственный вариант решения этой проблемы я вижу в использовании файла cache/pages_*.xml (_вместо астериска — md5-хэш от файла pages.xml, пример: pages_6e2e796fb59733d0d612efa513f0a1e0.xml_).

В отличие от pages.xml в тех местах, где в uri был указан какой-либо вызов метода (`/{LinkUtility::GetNewsBaseUrl()}`), в pages_*.xml находится результат этого вызова в виде uri, по которым eazestorm уже умеет искать. Поэтому можно при наличии файла pages_*.xml использовать для поиска именно его. 

Этот файл создаётся при первом обращении к сайту, но может быть замещён файлом pages_*.xml с другим хэшом в названии, при этом старый файл удаляется, то есть, одновременно в директории web/cache может быть не больше одного файла вида pages_*.xml.

Примеры файлов [pages.xml](https://dl.dropboxusercontent.com/u/931412/pages.xml) и [pages_96a70f38754fcdb129b8f885ca15fb8b.xml](https://dl.dropboxusercontent.com/u/931412/pages_96a70f38754fcdb129b8f885ca15fb8b.xml).

**Comment by hrefr** [comment]
Спасибо.
У меня только один вопрос: стоит ли искать uri в кеше, если md5 текущего pages.xml не совпадает?
Для обычных uri понятно, что не стоит, но проверять ли старый кеш для uri, компилируемых LinkUtility?

**Comment by antyblin** [comment]
Может, это в конфиги вынести?

**Comment by hrefr** [comment]
Можно добавить в настройки проекта галочку "Check pages.xml hash sum  before resolving dynamic URIs".
Какое будет значение по-умолчанию?

**Comment by antyblin** [comment]
По умолчанию кеш должен использоваться только при совпадении md5.
